### PR TITLE
Update DG

### LINKED ISSUE #25: Update DG
Add the following to the DG, based on your project notes from the previous weeks. No need to update other sections, for now.
 - Some examples of these can be found in the [AB3 Developer Guide](https://se-education.org/addressbook-level3/DeveloperGuide.html#product-scope).
- Target user profile, value proposition, and user stories: Update the target user profile and value proposition to match the project direction you have selected. Give a list of the user stories (and update/delete existing ones, if applicable), including priorities. This can include user stories considered but will not be included in the final product.
- Use cases: Give a few representative use cases (textual form) that need multiple steps to complete. e.g. Adding a tag to a person (assume the user needs to find the person first)
- Non-functional requirements: Note: Many of the given project constraints can be considered NFRs. You can add more. e.g. performance requirements, usability requirements, scalability requirements, etc.
- Glossary: Define terms that are worth recording.

### PR DESCRIPTION
**Pull request by uniqly**
Resolves #25

### CODE REVIEW

**Comment by blanklogic** [comment]
Here's my suggestion for NFR and Glossary
```markdown
### Non-Functional Requirements

1. Should work on any mainstream OS as long as it has Java 17 or above installed.
2. Should be able to handle up to 1000 companies without a noticeable slowdown in typical usage.
3. A user with above-average typing speed for regular English text should be able to accomplish most tasks faster using commands than using a GUI.
4. The system should respond to user commands within 1 second for most operations.
5. The application should allow for seamless data export in common formats (e.g., CSV or JSON) for external backup or sharing.

---

### Glossary

- **Mainstream OS**: Windows, Linux, Unix, macOS.
- **Private contact detail**: A contact detail that is not meant to be shared with others.
- **CLI**: Command Line Interface, a method of interacting with software using typed commands rather than a graphical interface.
- **PR (Pull Request)**: A request submitted by a contributor to merge code changes into a repository's main codebase, commonly used in GitHub for code reviews and collaboration.
```

**Comment by uniqly** [comment]
> Here's my suggestion for NFR and Glossary
> 
> ```
> ### Non-Functional Requirements
> 
> 1.  Should work on any _mainstream OS_ as long as it has Java `17` or above installed.
> 2.  Should be able to hold up to 1000 persons without a noticeable sluggishness in performance for typical usage.
> 3.  A user with above average typing speed for regular English text (i.e. not code, not system admin commands) should be able to accomplish most of the tasks faster using commands than using the mouse.
> 4. The system should respond to user commands without noticeable lag for most operations.
> 5. The application should allow for seamless data export in common formats (e.g., CSV or JSON) for external backup or sharing.
> 
> ---
> 
> ### Glossary
> 
> - **Mainstream OS**: Windows, Linux, Unix, macOS.
> - **Private contact detail**: A contact detail that is not meant to be shared with others.
> - **CLI**: Command Line Interface, a method of interacting with software using typed commands rather than a graphical interface.
> - **PR (Pull Request)**: A request submitted by a contributor to merge code changes into a repository's main codebase, commonly used in GitHub for code reviews and collaboration.
> ```

Thanks for the suggestions, I have added them to the PR!

**Review by blanklogic — CHANGES_REQUESTED** [review]
Sorry for the trouble yet again. Some suggested changes to the following links to ensure we are tracking this repo and not the upstream.
```diff
Line 38
- **`Main`** (consisting of classes [`Main`](https://github.com/se-edu/addressbook-level3/tree/master/src/main/java/seedu/address/Main.java) and [`MainApp`](https://github.com/se-edu/addressbook-level3/tree/master/src/main/java/seedu/address/MainApp.java)) is in charge of the app launch and shut down.
+ **`Main`** (consisting of classes [`Main`](https://github.com/AY2425S1-CS2103T-T09-1/tp/tree/master/src/main/java/seedu/address/Main.java) and [`MainApp`](https://github.com/AY2425S1-CS2103T-T09-1/tp/tree/master/src/main/java/seedu/address/MainApp.java)) is in charge of the app launch and shut down.

Line 70
- The **API** of this component is specified in [`Ui.java`](https://github.com/se-edu/addressbook-level3/tree/master/src/main/java/seedu/address/ui/Ui.java)
+ The **API** of this component is specified in [`Ui.java`](https://github.com/AY2425S1-CS2103T-T09-1/tp/tree/master/src/main/java/seedu/address/ui/Ui.java)

Line 76
- The `UI` component uses the JavaFx UI framework. The layout of these UI parts are defined in matching `.fxml` files that are in the `src/main/resources/view` folder. For example, the layout of the [`MainWindow`](https://github.com/se-edu/addressbook-level3/tree/master/src/main/java/seedu/address/ui/MainWindow.java) is specified in [`MainWindow.fxml`](https://github.com/se-edu/addressbook-level3/tree/master/src/main/resources/view/MainWindow.fxml)
+ The `UI` component uses the JavaFx UI framework. The layout of these UI parts are defined in matching `.fxml` files that are in the `src/main/resources/view` folder. For example, the layout of the [`MainWindow`](https://github.com/AY2425S1-CS2103T-T09-1/tp/tree/master/src/main/java/seedu/address/ui/MainWindow.java) is specified in [`MainWindow.fxml`](https://github.com/AY2425S1-CS2103T-T09-1/tp/tree/master/src/main/resources/view/MainWindow.fxml)

Line 87
- **API** : [`Logic.java`](https://github.com/se-edu/addressbook-level3/tree/master/src/main/java/seedu/address/logic/Logic.java)
+ **API** : [`Logic.java`](https://github.com/AY2425S1-CS2103T-T09-1/tp/tree/master/src/main/java/seedu/address/logic/Logic.java)

Line 119
- **API** : [`Model.java`](https://github.com/se-edu/addressbook-level3/tree/master/src/main/java/seedu/address/model/Model.java)
+ **API** : [`Model.java`](https://github.com/AY2425S1-CS2103T-T09-1/tp/tree/master/src/main/java/seedu/address/model/Model.java)

Line 142
- **API** : [`Storage.java`](https://github.com/se-edu/addressbook-level3/tree/master/src/main/java/seedu/address/storage/Storage.java)
+ **API** : [`Storage.java`](https://github.com/AY2425S1-CS2103T-T09-1/tp/tree/master/src/main/java/seedu/address/storage/Storage.java)
```

**Comment by uniqly** [comment]
> Sorry for the trouble yet again. Some suggested changes to the following links to ensure we are tracking this repo and not the upstream.

@blanklogic, resolve the links referencing AB3. Good catch! 👍

**Review by blanklogic — APPROVED** [review]
Overall LGTM!

**Review by realqijun — APPROVED** [review]
Well done on the Developer Guide. The use cases and user stories are well defined. LGTM

**Pull request merged**
