### PR TITLE
Update README.md to match InternBuddy

### LINKED ISSUE #6: Update README page to match InternBuddy
# Updating README
- Add a UI mockup of our intended final product
- Update the link of the GitHub Actions build status badge so that it reflects the build status of our team repo
- Acknowledge the original source of the code
- Update all remaining contents of the page to match InternBuddy

### PR DESCRIPTION
**Pull request by blanklogic**
# Updating README
- Update the link of the GitHub Actions build status badge so that it reflects the build status of our team repo
- Acknowledge the original source of the code
- Update all remaining contents of the page to match InternBuddy

Resolves #6

### CODE REVIEW

**Review by uniqly — COMMENTED** [review]
Overall LGTM! 
Are we waiting for the updated Ui mock-up for this PR or will that be separate issue?

**Review by uniqly — APPROVED** [review]
Overall LGTM! 😃

**Comment by blanklogic** [comment]
> Are we waiting for the updated Ui mock-up for this PR or will that be separate issue?

The plan is to have the Ui mock-up be updated along with the existing commits in this pull request so as to allow us to easily keep track of the changes made for the same purpose.

**Review by uniqly — APPROVED** [review]
LGTM

**Comment by realqijun** [comment]
Love what you did with the README.md!
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠞⠉⠉⠉⠉⠉⠉⠙⠓⢦⣄
⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⠏⢠⣤⡶⠶⠶⠶⠶⣤⣄⠀⠹⣧⡀
⠀⠀⠀⠀⠀⠀⠀⠀⣸⠟⠀⠸⣿⣦⣄⣀⣠⣤⣤⡿⠀⠀⠘⣧
⠀⠀⠀⠀⠀⠀⠀⢰⡟⠀⠀⠀⠀⠉⠉⠉⠉⠉⠁⠀⠀⠀⠀⢹⡄
⠀⠀⠀⠀⠀⠀⠀⣼⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇
⠀⠀⠀⠀⠀⠀⢀⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⡇
⠀⠀⠀⠀⠀⠀⣸⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣇
⠀⠀⠀⠀⠀⢀⡿⠀⠀⠀⢠⡶⠒⠒⠒⠒⠲⣦⡀⠀⠀⠀⠀⠀⣿
⠀⣀⣠⣄⣀⣼⡇⠀⠀⠀⢸⡇⠀⠀⠀⠀⠀⢸⡇⠀⠀⠀⠀⠀⡇
⠸⣏⡀⠀⠀⠈⠀⠀⠀⣀⣼⡇⠀⠀⣀⣀⣠⣼⠃⠀⠀⠀⠀⠀⡏
⠀⠈⠛⠛⠒⠒⠒⠛⠛⠉⠁⠀⠀⣾⠉⠀⠀⠀⠀⠀⠀⠀⢀⣰⠇
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠛⠒⠒⠒⠚⠛⠉⠉

**Review by realqijun — APPROVED** [review]
Good Work!

**Pull request merged**
